- src/main/java/com/genius/todoffin/TodoffinApplication.java
- src/main/java/com/genius/todoffin/common/domain/BaseTimeEntity.java
- src/main/java/com/genius/todoffin/user/domain/Role.java
- src/main/java/com/genius/todoffin/user/domain/User.java
- src/main/java/com/genius/todoffin/user/repository/UserRepository.java
- src/test/java/com/genius/todoffin/user/repository/UserRepositoryTest.java
</br>
feat/social-login-> feat/social-login/common
</br>
소셜로그인에 필요한 User Entity 및 Repository 개발
</br>
- Junit5를 이용한 단위 테스트 실행 (2/2 성공)
</br>
ex) #10 
</br>
> Feat: 소셜로그인에 필요한 User Entity 및 Repository 개발

- src/main/java/com/genius/security/config/SecurityConfig.java
- src/main/java/com/genius/security/constants/AuthProvider.java
</br>
ex) feat/social-login/setting -> feat/social-login
</br>
Spring Security, OAuth 2.0에서 필요한 설정 진행
</br>
</br>
ex) #9 
</br>
SecurityConfig의 코드들 중, 객체가 없어 주석으로 처리한 부분이 있습니다. 해당 부분 참고하여 리뷰 부탁드립니다.
> Feat: Spring Security, OAuth 2.0에서 필요한 설정 진행

- src/main/java/com/genius/gitget/challenge/home/dto/HomeInstanceResponse.java
- src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
- src/main/java/com/genius/gitget/challenge/instance/dto/search/InstanceSearchResponse.java
- src/test/java/com/genius/gitget/challenge/home/controller/HomeControllerTest.java
- src/test/java/com/genius/gitget/challenge/home/service/HomeServiceTest.java
- src/test/java/com/genius/gitget/challenge/instance/repository/InstanceRepositoryTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
hotfix/55-instance-entity-name-fix -> main
</br>
Instance entity 이름 변경했습니다. 
</br>
</br>
#55 
</br>
> [HOTFIX] Instance entity 이름 변경

- src/main/java/com/genius/gitget/admin/topic/service/TopicService.java
- src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
- src/test/java/com/genius/gitget/admin/topic/controller/TopicControllerTest.java
- 토픽이 인스턴스를 가질 때 해당 토픽을 삭제하려 할 때의 예외처리
- ErrorCode 추가
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
test/43-admin-page -> main
</br>
- 토픽이 인스턴스를 가질 때 해당 토픽을 삭제하려 할 때의 예외처리 
- ErrorCode 추가 
</br>
</br>
ex) #이슈번호, #이슈번호
</br>
> [FEAT] 토픽 삭제 예외 기능 추가

- src/main/java/com/genius/gitget/global/security/config/SecurityConfig.java
- src/test/java/com/genius/gitget/global/security/config/SecurityConfigTest.java
- src/test/java/com/genius/gitget/util/WithMockCustomUserSecurityContextFactory.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/74-admin-authentication`→ `main`
</br>
</br>
</br>
#74 
</br>
>
> [FEAT] 어드민 API 접근 권한 설정

- src/main/java/com/genius/gitget/challenge/item/domain/Item.java
- src/main/java/com/genius/gitget/challenge/item/domain/ItemCategory.java
- src/main/java/com/genius/gitget/challenge/item/domain/UserItem.java
- src/main/java/com/genius/gitget/challenge/item/repository/ItemRepository.java
- src/main/java/com/genius/gitget/challenge/item/repository/UserItemRepository.java
- src/main/java/com/genius/gitget/challenge/user/domain/User.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/88-item-entity` → `main`
</br>
아이템과 관련있는 Entity 및 Repository 작성
</br>
</br>
#88 
</br>
>
> [FEAT] Item 관련 Entity 및 Repository 작성

- src/main/java/com/genius/gitget/admin/topic/controller/TopicController.java
- src/main/java/com/genius/gitget/admin/topic/domain/Topic.java
- src/main/java/com/genius/gitget/admin/topic/service/TopicService.java
- src/main/java/com/genius/gitget/challenge/instance/controller/InstanceController.java
- src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
- src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceCreateRequest.java
- src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceDetailResponse.java
- src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceUpdateRequest.java
- src/main/java/com/genius/gitget/challenge/instance/repository/InstanceRepository.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
- src/main/java/com/genius/gitget/challenge/user/domain/User.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
ex) feat/login -> dev
</br>
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
</br>
</br>
ex) #이슈번호, #이슈번호
</br>
> [FEAT] certification_method entity 추가 

- src/main/java/com/genius/gitget/challenge/user/service/UserService.java
- src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
- src/test/java/com/genius/gitget/challenge/instance/repository/InstanceRepositoryTest.java
- src/test/java/com/genius/gitget/challenge/user/service/UserServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`fix/92-duplicate-register` → `main`
</br>
</br>
</br>
#92 
</br>
>
> [BUG/FIX] 이미 회원가입되어있는 사용자에 대해, 회원가입 재시도를 막도록 변경

- src/main/java/com/genius/gitget/global/security/controller/AuthController.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/94-logout-bug` → `main`
</br>
logout API 요청 시 발생하던 버그를 픽스했습니다.
</br>
</br>
#94 
</br>
> [BUG/FIX] 로그아웃 API 요청 시 에러 발생

- src/main/java/com/genius/gitget/challenge/certification/service/CertificationService.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/101-total-certification-bug` → `main`
</br>
전체 인증 현황 조회 시, 전체 기간이 아닌 일주일 단위로 전달되던 버그를 수정했습니다.
`convertToCertificationResponse`에서 시작 일자를 무조건 주의 월요일로 설정한 후, 변환 작업 진행
해당 메서드를 주간/전체 인증 현황에서 같이 사용하고 있기 때문에, 시작 일자를 계산한 후 전달하도록 변경
</br>
</br>
#101 
</br>
>
> [BUG/FIX] 전체 인증 현황 조회 시, 기간이 제대로 전달되지 않는 버그

- src/main/java/com/genius/gitget/profile/controller/ProfileController.java
- src/main/java/com/genius/gitget/profile/dto/UserInterestUpdateRequest.java
- src/main/java/com/genius/gitget/profile/service/ProfileService.java
- src/main/resources/data.sql
- src/test/java/com/genius/gitget/profile/service/ProfileServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
hotfix/110-user-interest
</br>
- 사용자 관심사 수정 시 생기는 이슈 해결
</br>
```
{
"code": "OK",
"resultCode": 200,
"message": "요청이 정상적으로 처리되었습니다.",
"data": {
"tags": [
"BE",
"AI"
]
}
}
```
</br>
#110 
</br>
> [HOTFIX] type definition error 해결

- src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
- src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
- src/test/java/com/genius/gitget/challenge/instance/repository/InstanceRepositoryTest.java
- src/test/java/com/genius/gitget/challenge/instance/service/InstanceServiceTest.java
- instanceUUID entity 추가
- 테스트 코드 작성
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
feat/112-instance-uuid -> main
</br>
</br>
</br>
#112 
</br>
> [FEAT] instance 생성 시 uuid 추가

- src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
- src/test/java/com/genius/gitget/challenge/instance/service/InstanceServiceTest.java
- 인스턴스 삭제 시 Optional로 받는 file 객체 코드 수정
- 테스트 코드 작성
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
refactor/142-instance-delete -> main
</br>
instanceService 인스턴스 삭제 메서드 수정 및 테스트 코드 작성했습니다. 
</br>
</br>
ex) #이슈번호, #이슈번호
</br>
> [REFACTOR] 인스턴스 삭제

- src/main/java/com/genius/gitget/challenge/certification/controller/CertificationController.java
- src/main/java/com/genius/gitget/challenge/certification/dto/WeekResponse.java
- src/main/java/com/genius/gitget/challenge/certification/service/CertificationService.java
- src/main/java/com/genius/gitget/challenge/user/dto/UserProfileInfo.java
- src/main/java/com/genius/gitget/challenge/user/service/UserService.java
- src/main/java/com/genius/gitget/global/security/controller/AuthController.java
- src/test/java/com/genius/gitget/challenge/certification/service/CertificationServiceTest.java
- src/test/java/com/genius/gitget/challenge/user/service/UserServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`refactor/149-improve-certification-service` → `main`
</br>
> `CertificationService`의 전체 인증 조회(TotalCertification)과 주간 인증 조회(WeekCertification)과 관련된 로직을 개선합니다.
</br>
</br>
#149 
</br>
>
> [REFACTOR] CertificationService의 전체/주간인증 조회 로직 개선

- .github/workflows/prTest.yml
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/170-add-PR-workflow` → `main`
</br>
</br>
</br>
#170 
</br>
>
> [FEAT] main 브랜치에 PR 요청 시, 테스트 자동화 워크플로우 적용

- .github/workflows/main.yml
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
ex) feat/login -> dev
</br>
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
</br>
</br>
ex) #이슈번호, #이슈번호
</br>
> [CHORE] main yml 수정

- .github/workflows/main.yml
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
feat/185-slack-webhook -> main 
</br>
* Slack Webhook URL 발급 
* webhook 받을 slack app template 설정
* Secrets 변수 추가 
* Main.yml 파일에 Slack webhook 코드 추가 
</br>
</br>
#185 
</br>
> [FEAT] Slack Webhook 적용

- .github/workflows/main.yml
- appspec.yml
□ 기능 추가
□ 기능 삭제
□ 버그 수정
☑ 의존성, 환경 변수, 빌드 관련 코드 업데이트
</br>
`feat/194-deployment-automation` → `main`
</br>
`scripts` - `deploy.sh`가 실행됨에 따라 빌드 파일이 실행됩니다.
</br>
</br>
#194 
</br>
>
> [FEAT] 배포 자동화 적용

- README.md
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
kimdozzi-patch-1 -> main 
</br>
* Readme 파일 수정
</br>
</br>
</br>
> [CHORE] GitGet Readme 업데이트 

- src/main/java/com/genius/gitget/challenge/certification/service/CertificationFacadeService.java
- src/main/java/com/genius/gitget/challenge/user/controller/UserController.java
- src/main/java/com/genius/gitget/challenge/user/facade/UserFacade.java
- src/main/java/com/genius/gitget/challenge/user/facade/UserFacadeService.java
- src/main/java/com/genius/gitget/challenge/user/facade/UserServiceFacade.java
- src/main/java/com/genius/gitget/challenge/user/service/UserService.java
- src/main/java/com/genius/gitget/global/security/controller/AuthController.java
- src/main/java/com/genius/gitget/global/security/dto/AuthResponse.java
- src/main/java/com/genius/gitget/global/security/dto/SignupResponse.java
- src/main/java/com/genius/gitget/global/security/filter/JwtAuthenticationFilter.java
- src/main/java/com/genius/gitget/profile/service/ProfileFacadeService.java
- src/main/java/com/genius/gitget/store/item/domain/Item.java
- src/main/java/com/genius/gitget/store/item/service/OrdersService.java
- src/test/java/com/genius/gitget/challenge/user/service/UserFacadeTest.java
- src/test/java/com/genius/gitget/payment/service/PaymentServiceTest.java
- src/test/java/com/genius/gitget/util/security/WithMockCustomUserSecurityContextFactory.java
- src/test/java/com/genius/gitget/util/user/UserFactory.java
□ 기능 추가
□ 기능 삭제
☑ 리팩토링
□ 버그 수정
</br>
`refactor/258-user-facade-pattern` → `main`
</br>
> User 서비스 계층에 Facade 패턴을, 테스트 코드에 DCI 패턴을 적용합니다.
</br>
</br>
#258
</br>
>
> [REFACTOR] UserService 계층에 Facade pattern 적용

- src/main/java/com/genius/gitget/global/file/controller/FileTestController.java
- src/main/java/com/genius/gitget/global/file/dto/FileResponse.java
- src/main/java/com/genius/gitget/global/file/service/FileService.java
- src/main/java/com/genius/gitget/global/file/service/FilesManager.java
- src/main/java/com/genius/gitget/global/file/service/LocalFileService.java
- src/main/java/com/genius/gitget/global/file/service/S3FileService.java
- src/main/java/com/genius/gitget/global/util/config/AppConfig.java
- src/test/java/com/genius/gitget/global/file/domain/FilesTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/247-improve-file-performance` → `main`
</br>
>  파일(이미지) 정보를 반환하는 API의 성능을 개선합니다.
</br>
</br>
#247 
</br>
> [FEAT] 파일 시스템 성능 개선

- .github/workflows/main.yml
- .github/workflows/prTest.yml
- src/main/java/com/genius/gitget/challenge/certification/repository/CertificationRepository.java
□ 기능 추가
□ 기능 삭제
☑ 리팩토링
□ 버그 수정
☑ 의존성, 환경 변수, 빌드 관련 코드 업데이트
</br>
`refactor/improve-query` → `main`
</br>
</br>
</br>
</br>
> [REFACTOR]CertificationRepository 쿼리 성능 개선
