TeamTheGenius/GitGet_Server

- src/main/java/com/genius/gitget/security/controller/AuthController.java
- src/test/java/com/genius/gitget/security/controller/AuthControllerTest.java
- src/test/java/com/genius/gitget/util/TokenTestUtil.java
- src/test/java/com/genius/gitget/util/WithMockCustomUser.java
- src/test/java/com/genius/gitget/util/WithMockCustomUserSecurityContextFactory.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
feat/34-auth-anotation
</br>
/auth 를 제외한 controller API 테스트 시, 권한 관련 오류로 인해 테스트가 되지 않는 버그를 수정합니다.
커스텀 어노테이션을 생성하여 테스트가 용이하도록 합니다.
</br>
</br>
#34 
</br>
> commit만 하고 이후에 한 번에 push해야한다는 사실을 까먹고 commit-push까지 진행했습니다 ㅎㅎ;;
> 다음에는 한 번에 push 하도록 하겠습니다!
> [FEAT] Controller(API) 테스트 코드 작성에 필요한 유틸 개발

- src/main/java/com/genius/gitget/GitgetApplication.java
- src/main/java/com/genius/gitget/security/config/SecurityConfig.java
- src/main/java/com/genius/gitget/security/controller/AuthController.java
- src/main/java/com/genius/gitget/security/service/JwtService.java
- src/main/java/com/genius/gitget/security/service/JwtUtil.java
- src/main/java/com/genius/gitget/user/domain/User.java
- src/main/java/com/genius/gitget/util/exception/ErrorCode.java
- src/test/java/com/genius/gitget/file/service/FileUtilTest.java
- src/test/java/com/genius/gitget/file/service/FilesServiceTest.java
- src/test/java/com/genius/gitget/hits/HitsTest.java
- src/test/java/com/genius/gitget/security/service/JwtServiceTest.java
- src/test/java/com/genius/gitget/topic/TopicControllerTest.java
- src/test/java/com/genius/gitget/user/repository/UserRepositoryTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/44-fix-jwt-reissue-bug` → `main`
</br>
JWT 재발급 관련 버그 픽스했습니다.
</br>
</br>
#44 
</br>
> [FIX] JWT 재발급 관련 버그 픽스

- src/main/java/com/genius/gitget/global/file/controller/FilesController.java
- src/main/java/com/genius/gitget/global/file/dto/FileRequest.java
- src/main/java/com/genius/gitget/global/file/dto/FileResponse.java
- src/main/java/com/genius/gitget/global/file/service/FileUtil.java
- src/main/java/com/genius/gitget/global/file/service/FilesService.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`refactor/48-file-structure` → `main`
</br>
이미지 포함 시 다른 데이터를 포함하지 못했던 기존의 방식과는 달리, 이미지와 다른 데이터들을 같이 전달할 수 있게끔 합니다.
</br>
</br>
#48 
</br>
> [REFACTOR] 이미지/파일 요청과 응답 시 base64 인코딩하여 전달하도록 변경

- src/main/java/com/genius/gitget/global/security/config/SecurityConfig.java
- src/main/java/com/genius/gitget/global/security/filter/ExceptionHandlerFilter.java
- src/main/java/com/genius/gitget/global/security/handler/OAuth2SuccessHandler.java
- src/test/java/com/genius/gitget/global/security/config/SecurityConfigTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 리포트
☑ 버그 수정
</br>
`hotfix/57-JwtFilter-exception` → `main`
</br>
> `JwtAuthenticationFilter`에서 발생하는 예외(대체로 JWT 관련)에 대해 400번대 Code를 발생시켜야 하는데, 302번이 전달되어 기본 로그인 화면으로 리다이렉트 되고 있었습니다.  
> 추가적인 Filter 클래스(`ExceptionHandlerFilter`)를 통해 `JwtAuthenticationFilter`에서 발생한 예외에 따라 400번대를 전달하도록 했습니다.
</br>
</br>
#57 
</br>
> [HOTFIX] JWT Filter에서 예외 발생 시 처리하지 못하는 로직 수정

- src/main/java/com/genius/gitget/admin/topic/domain/Topic.java
- src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
- src/main/java/com/genius/gitget/challenge/user/domain/User.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/63-files-entity-cascade`→ `main`
</br>
Files 엔티티와 연관관계에 있는 User, Topic, Instance 엔티티에 영속성 전이 옵션과 고아 객체 옵션을 적용합니다.
</br>
</br>
#63 
</br>
> [FEAT] Files 엔티티 연관관계에 대해 영속성 전이 설정

- src/main/java/com/genius/gitget/admin/topic/service/TopicService.java
- src/main/java/com/genius/gitget/challenge/instance/controller/InstanceController.java
- src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceDetailResponse.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
- src/main/java/com/genius/gitget/global/file/dto/FileResponse.java
- src/main/java/com/genius/gitget/global/file/service/FileUtil.java
- src/main/java/com/genius/gitget/global/file/service/FilesService.java
- src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
- src/test/java/com/genius/gitget/global/file/service/FileUtilTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`hotfix/66-topic-delete-bug` → `main`
</br>
</br>
</br>
#66 
</br>
> Postman으로 직접 테스트 진행했을 때 정상작동 했으나, 혹시 제가 놓친 예외 부분이 있는지 한 번 확인 부탁드립니다!
> [BUG] Topic 삭제 요청 시, 삭제가 되지 않는 버그

- src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstancePagingResponse.java
- src/main/java/com/genius/gitget/global/file/service/FilesService.java
- 인스턴스 수정 API 요청 시, MultipartFile이 없을 때 처리하는 로직 보강
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`hotfix/71-instance-update-bug` → `main`
</br>
</br>
</br>
#71 
</br>
>
> [BUG] 인스턴스 수정 시, 수정이 되지 않는 버그

- src/main/java/com/genius/gitget/challenge/certification/service/CertificationService.java
- src/main/java/com/genius/gitget/challenge/certification/util/DateUtil.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/105-week-certification-period-bug` → `main`
</br>
</br>
</br>
#105 
</br>
>
> [BUG/FIX] 주간 인증 조회 API 기간 버그

- src/main/java/com/genius/gitget/challenge/certification/service/CertificationService.java
- src/main/java/com/genius/gitget/challenge/myChallenge/dto/RewardRequest.java
- src/main/java/com/genius/gitget/challenge/myChallenge/service/MyChallengeService.java
- src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
- src/test/java/com/genius/gitget/challenge/certification/service/CertificationServiceTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/104-passer-item-bug` → `main`
</br>
아이템 사용 후, 사용자의 아이템 보유 정보를 가지고 있는 `UserItem`의 `count`를 줄이지 않아 나타나던 버그였습니다.
`CertificationService`의 `passCertification`에서 count를 줄이는 로직을 추가했습니다.
</br>
</br>
#104
> fix: 인증 패스 아이템 사용 시, 아이템 개수가 줄어들지 않았던 버그 픽스

- src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
- src/main/java/com/genius/gitget/challenge/instance/dto/detail/InstanceResponse.java
- src/main/java/com/genius/gitget/challenge/instance/dto/detail/LikesInfo.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceDetailService.java
- src/main/java/com/genius/gitget/challenge/likes/repository/LikesRepository.java
- src/test/java/com/genius/gitget/challenge/instance/service/InstanceDetailServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/115-add-likes-instance-details` → `main`
</br>
</br>
</br>
#115 
</br>
>
> [FEAT] 챌린지 상세 페이지 응답 시 '좋아요'와 관련된 데이터 추가

- src/main/java/com/genius/gitget/global/security/controller/AuthController.java
- src/main/java/com/genius/gitget/global/security/dto/AuthResponse.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/113-add-user-data` → `main`
</br>
`/auth` 를 통해 JWT 발급 API 요청에 대한 응답데이터에 사용자의 정보(ROLE)을 전달
JWT API의 응답 데이터에 사용자의 데이터(역할) 추가
</br>
</br>
#113 
</br>
>
> [FEAT] JWT 요청 시, 사용자에 대한 정보 같이 전달

- src/main/java/com/genius/gitget/challenge/user/controller/UserController.java
- src/main/java/com/genius/gitget/challenge/user/service/UserService.java
- src/test/java/com/genius/gitget/challenge/user/service/UserServiceTest.java
- src/test/java/com/genius/gitget/util/WithMockCustomUser.java
- src/test/java/com/genius/gitget/util/WithMockCustomUserSecurityContextFactory.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/123-save-profile-image` → `main`
</br>
</br>
</br>
#123 
</br>
> 요구사항은 아니고 참고사항입니다!
> 개발을 하다보니 FilesService에 개선사항이 보여서 이슈로 등록 후, 추후 수정할 예정입니다!
> [FEAT] 회원가입 시 프로필 이미지를 받아 저장하는 기능

- src/main/java/com/genius/gitget/challenge/certification/controller/CertificationController.java
- src/main/java/com/genius/gitget/challenge/certification/service/CertificationService.java
- src/main/java/com/genius/gitget/challenge/certification/util/DateUtil.java
- src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
- src/test/java/com/genius/gitget/challenge/certification/service/CertificationServiceTest.java
- src/test/java/com/genius/gitget/challenge/certification/util/DateUtilTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/121-certification-bug-fix` → `main`
</br>
</br>
`UserControllerTest`에 실패 1건 존재. 수정 예정
</br>
#121 
</br>
>
> [FIX] 인증 시스템 관련 버그 픽스

- src/main/java/com/genius/gitget/challenge/user/domain/User.java
- src/main/java/com/genius/gitget/challenge/user/service/UserService.java
- src/test/java/com/genius/gitget/challenge/user/controller/UserControllerTest.java
- src/test/java/com/genius/gitget/challenge/user/service/UserServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/127-signup-role` → `main`
</br>
> 회원가입 시, 개발자인 경우 자동으로 운영진으로 설정하는 기능을 추가합니다.
</br>
</br>
#127 
</br>
>
> [FEAT] 회원가입 시, 개발자에 해당하는 깃허브 계정인 경우 운영진으로 설정 

- src/main/java/com/genius/gitget/challenge/certification/dto/CertificationResponse.java
- src/main/java/com/genius/gitget/challenge/certification/service/CertificationService.java
- src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
- src/test/java/com/genius/gitget/challenge/certification/service/CertificationServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`fix/136-certification-week-bug` → `main`
</br>
> 주간 인증 현황 조회 API와 관련된 버그를 픽스합니다
확인 결과, 데이터 존재 여부 확인 로직에 문제가 있어 해당 로직 분리
</br>
</br>
#136 
</br>
>
> [FIX] 주간 인증 현황 조회 버그 픽스

- src/main/java/com/genius/gitget/challenge/certification/dto/CertificationResponse.java
- src/main/java/com/genius/gitget/challenge/certification/service/CertificationService.java
- src/test/java/com/genius/gitget/challenge/certification/service/CertificationServiceTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/138-total-certification-bug` → `main`
</br>
</br>
`UserController`의 `Multipart` 관련 API 테스트에 오류 존재. 수정 예정
</br>
#138 
</br>
> 이후에 코드 리팩토링 예정입니다
> [FIX] 전체 인증 조회 버그 픽스

- src/main/java/com/genius/gitget/challenge/certification/domain/Certification.java
- src/main/java/com/genius/gitget/challenge/participant/domain/Participant.java
- src/main/java/com/genius/gitget/challenge/user/domain/User.java
- src/main/java/com/genius/gitget/profile/dto/UserSignoutRequest.java
- 사용자가 아이템을 구매했거나, 챌린지를 참여한 이력이 있을 경우 제약조건 에러가 발생
- certification-participant, user-payment, user-orders 관계 재설정 후 버그 수정 완료
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
bug/139-user-withdraw -> main
</br>
- 유저 로그아웃 버그 수정
</br>
</br>
#139 
</br>
> bug: 사용자 회원 탈퇴

- src/main/java/com/genius/gitget/challenge/certification/service/CertificationService.java
- src/test/java/com/genius/gitget/challenge/instance/service/InstanceDetailServiceTest.java
- src/test/java/com/genius/gitget/challenge/user/controller/UserControllerTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/145-today-certification-bug` → `main`
</br>
> 오늘의 인증 갱신 API 요청 시, 발생하는 버그를 픽스합니다
> 사용자가 생성한 PR의 내용(Body)가 존재하지 않을 때 .getBody()가 null이라며 발생하던 예외에 대해 추가적인 처리를 진행했습니다.
</br>
</br>
#145 
</br>
>
> [FIX] 오늘의 인증 갱신 API 버그 픽스

- src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
- src/main/java/com/genius/gitget/global/util/exception/FileExceptionHandler.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`fix/159-add-file-exception-handler` → `main`
</br>
</br>
</br>
#159 
</br>
>
> [FIX] 파일 저장 시, 특정 용량 이상의 파일이 전달되었을 때 발생하는 예외 추가 처리

- .github/workflows/test-task.yml
- build.gradle
- src/main/java/com/genius/gitget/global/file/service/FileUtil.java
- src/main/java/com/genius/gitget/global/file/service/S3FileManager.java
- src/main/java/com/genius/gitget/global/util/config/AppConfig.java
- src/main/java/com/genius/gitget/global/util/config/S3Config.java
- src/test/java/com/genius/gitget/challenge/instance/controller/InstanceControllerTest.java
- src/test/java/com/genius/gitget/challenge/likes/controller/LikesControllerTest.java
- src/test/java/com/genius/gitget/profile/controller/ProfileControllerTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/161-aws-s3-image` → `main` 
</br>
</br>
</br>
#161 
</br>
>
> [FEAT] AWS S3 이미지 관련 기능 개발

- src/main/java/com/genius/gitget/challenge/instance/dto/search/InstanceSearchResponse.java
- src/main/java/com/genius/gitget/challenge/instance/repository/SearchRepositoryCustom.java
- src/main/java/com/genius/gitget/challenge/instance/repository/SearchRepositoryImpl.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceSearchService.java
- src/test/java/com/genius/gitget/challenge/instance/repository/InstanceSearchRepositoryTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/167-search-not-contain-fileResponse` → `main`
</br>
> 인스턴스를 검색하는 API(`POST /api/challenges/search`) 에서 인스턴스의 파일 이미지가 전달되지 않는 버그를 픽스합니다.
</br>
</br>
#167
</br>
>
> [FIX] 인스턴스 검색 결과에 인스턴스의 파일 정보가 넘어오지 않는 버그 픽스

- build.gradle
- src/main/java/com/genius/gitget/challenge/likes/service/LikesService.java
- src/test/java/com/genius/gitget/challenge/likes/service/LikesServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
bug/168-like -> dev
</br>
좋아요 목록 조회 시, 설정한 pageNumber와 size에 관계없이 전체 조회가 되는 부분을 수정했습니다.
</br>
</br>
#168 
</br>
> [BUG] 좋아요 목록 조회 시 발생하는 버그 수정

- .github/workflows/main.yml
- src/main/java/com/genius/gitget/challenge/myChallenge/controller/MyChallengeController.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
feat/177-aws-s3-issue -> main
</br>
* AWS S3 bucket CORS 설정을 추가하였습니다.
* Request가 들어오는 challenge controller에 추가 코드를 작성하였습니다. 
</br>
</br>
#177 
</br>
> [FEAT] AWS S3 파일 저장 이슈 해결

- src/main/java/com/genius/gitget/global/file/dto/FileResponse.java
- src/main/java/com/genius/gitget/global/file/service/FileManager.java
- src/main/java/com/genius/gitget/global/file/service/FileUtil.java
- src/main/java/com/genius/gitget/global/file/service/LocalFileManager.java
- src/main/java/com/genius/gitget/global/file/service/S3FileManager.java
- src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
- src/test/java/com/genius/gitget/global/file/service/FileUtilTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`refactor/178-change-file-response` → `main`
</br>
만일, 원본 파일이 존재하지 않는 경우에는 `FILE_NOT_EXIST` 예외를 발생하도록 처리
→ 생성 API가 분리되어 있어, 인스턴스를 생성되고 파일은 저장되지 않는 문제점 발견 && 프론트측에 추가 처리 요청 완료
</br>
</br>
#178 #179 
</br>
>
> [REFACTOR] 파일이 저장소에 존재하지 않을 때에 대한 응답 데이터 리팩토링 및 추가 예외 처리

- src/main/java/com/genius/gitget/challenge/instance/repository/InstanceRepository.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceHomeService.java
- src/test/java/com/genius/gitget/challenge/home/service/InstanceHomeServiceTest.java
- src/test/java/com/genius/gitget/challenge/instance/repository/InstanceRepositoryTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/180-recommend-bug-fix` → `main`
</br>
> 홈화면에서 추천 챌린지가 제대로 전달되지 않는 버그 픽스
> 
> 🔥 버그 원인
> 사용자의 관심 태그의 개수 <= 인스턴스 관심 태그의 개수 일 때 문제 발생
> 사용자의 관심 태그를 split해서 List<String>으로 전달하는데, `i.tags in :userTags` 쿼리문에서 문제가 발생 (in절은 일치해야하기 때문)
</br>
</br>
#180
</br>
>
> [FIX] 추천 챌린지가 제대로 전달되지 않는 버그 픽스

- src/main/java/com/genius/gitget/store/item/controller/ItemController.java
- src/main/java/com/genius/gitget/store/item/domain/Item.java
- src/main/java/com/genius/gitget/store/item/dto/ItemResponse.java
- src/main/java/com/genius/gitget/store/item/repository/ItemRepository.java
- src/main/java/com/genius/gitget/store/item/service/ItemProvider.java
- src/main/resources/data.sql
- src/test/java/com/genius/gitget/challenge/item/service/ItemProviderTest.java
- src/test/java/com/genius/gitget/challenge/item/service/ItemServiceTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/188-item-identifier-bug` → `main`
</br>
> FE에서 Item의 식별 코드(현재에는 item_id)를 전달받아 식별 코드에 해당하는 이미지를 사용하는데,
> `data.sql`을 통해 아이템들을 저장하는 과정에서 식별 코드가 제대로 설정되지 않아, FE에서 적절한 이미지를 사용하지 못하는 버그를  픽스합니다.
> 
> 식별 코드를 담당하는 column을 새로 만들고, `data.sql`의 insert문도 적절하게 변경합니다.
DB table의 구조가 변경되기 때문에, 추후 `main`, `production` 브랜치에 merge 이후 Local / Production 환경의 DB를 수정해야 합니다.
</br>
</br>
#188 
</br>
> Item 테이블에서 식별용으로 사용할 Column의 이름을 `identifier`로 설정했는데, 더 좋은 이름이 있을까요?
> [FIX] FE에서 Item을 식별하는 코드가 제대로 설정되지 않는 버그 픽스

- src/main/java/com/genius/gitget/challenge/instance/controller/InstanceDetailController.java
- src/main/java/com/genius/gitget/challenge/instance/dto/detail/JoinRequest.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceDetailService.java
- src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
- src/main/java/com/genius/gitget/global/util/exception/SuccessCode.java
- src/test/java/com/genius/gitget/challenge/instance/service/InstanceDetailServiceTest.java
- src/test/java/com/genius/gitget/challenge/instance/service/ProgressServiceTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/193-challenge-join-condition` → `main`
</br>
> 당일에 시작하는 챌린지에 참여할 수 있는 버그를 수정합니다.
> As-Is: 당일에 시작하는 챌린지에 참여할 수 있음
> To-be: 당일에 시작하는 챌린지에 참여할 수 없음
</br>
</br>
#193 
</br>
>
> [FIX] 당일에 시작하는 챌린지에 참여할 수 있는 버그 픽스

- src/main/resources/data.sql
- src/test/java/com/genius/gitget/challenge/item/service/ItemServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/190-add-profile-frame` → `main`
</br>
> `data.sql`의 `insert`문에 프로필 프레임 3개 추가
기존의 아이템 뒤에 추가로 3개의 항목(불태워라 프레임, 끈적이는 프레임, 무섭지롱 프레임)이 추가되었습니다.
</br>
</br>
#190 
</br>
>
> [FEAT] 프로필 프레임 아이템 추가

- src/main/java/com/genius/gitget/challenge/instance/dto/detail/LikesInfo.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceDetailService.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`bug/192-like-count` → `main`
</br>
</br>
</br>
#192
</br>
>
> [FIX] 인스턴스 상세 조회 시 좋아요 개수 버그 픽스

- src/main/java/com/genius/gitget/schedule/service/ProgressService.java
- src/test/java/com/genius/gitget/challenge/instance/service/ProgressServiceTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/202-progress-update-scheduler` → `main`
</br>
</br>
</br>
#202 
</br>
>
> [FIX] 챌린지 시작 당일이 되었을 때 상태가 업데이트 되도록 버그 픽스

- src/main/java/com/genius/gitget/challenge/certification/controller/CertificationController.java
- src/main/java/com/genius/gitget/challenge/certification/controller/GithubController.java
- src/main/java/com/genius/gitget/challenge/certification/service/GithubProvider.java
- src/main/java/com/genius/gitget/challenge/certification/util/DateUtil.java
- src/main/java/com/genius/gitget/challenge/instance/controller/InstanceController.java
- src/main/java/com/genius/gitget/challenge/instance/controller/InstanceDetailController.java
- src/main/java/com/genius/gitget/challenge/instance/dto/detail/InstanceResponse.java
- src/main/java/com/genius/gitget/challenge/myChallenge/controller/MyChallengeController.java
- src/main/java/com/genius/gitget/schedule/controller/ProgressController.java
- src/main/java/com/genius/gitget/schedule/service/ScheduleService.java
- src/main/java/com/genius/gitget/store/item/controller/ItemController.java
- src/test/java/com/genius/gitget/challenge/certification/util/DateUtilTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/204-PR-recognize-bug` → `main`
</br>
ZonedDateTime을 활용하여 시스템의 타임존을 고려하여 KST로 변환하는 메서드 작성
</br>
</br>
#204
</br>
>
> [FIX] 00시~오전 동안 PR 인식을 못하는 버그 픽스

- src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceDetailService.java
- src/main/java/com/genius/gitget/challenge/participant/service/ParticipantProvider.java
- src/main/java/com/genius/gitget/profile/service/ProfileService.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/211-instance-cancel-bug` → `main`
</br>
AS-IS: `get(i)`를 통해 원소에 접근 가능
TO-BE: `for (Participant participant : participantInfos)`에서 바로 participant를 통해 원소에 접근 가능
</br>
</br>
#211
</br>
> 코드의 가독성을 고려하면서 작성해봤는데, 보시고 어떤지 피드백 해주시면 좋을 것 같아요!! :)
> [FIX] 인스턴스 참가 취소 시 인스턴스 참여 인원, 상태 변화에 대한 버그 픽스

- src/main/java/com/genius/gitget/challenge/myChallenge/service/MyChallengeService.java
- src/main/java/com/genius/gitget/challenge/participant/repository/ParticipantRepository.java
- src/main/java/com/genius/gitget/challenge/participant/service/ParticipantProvider.java
- src/test/java/com/genius/gitget/challenge/participant/service/ParticipantProviderTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/228-myChallange-done-list` → `main`
</br>
> 실패한 챌린지인 경우(도중 포기, 인증 달성율 도달 못함) `마이페이지`의 완료에는 카운트되지만, `마이챌린지`의 완료 탭에는 나타나지 않는 버그 픽스
</br>
</br>
#228 
</br>
> [FIX] 실패한 챌린지 경우 마이챌린지의 완료 탭에 나타나지 않는 버그 픽스

- src/main/java/com/genius/gitget/challenge/myChallenge/dto/DoneResponse.java
- src/main/java/com/genius/gitget/challenge/myChallenge/service/MyChallengeService.java
- src/test/java/com/genius/gitget/challenge/myChallenge/service/MyChallengeServiceTest.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/227-archivement-rate-bug` → `main`
</br>
</br>
</br>
#227 
</br>
>
> [FIX] 실패한 챌린지에 대해 달성율이 나오지 않는 버그 픽스

- src/main/java/com/genius/gitget/challenge/user/service/UserService.java
- src/main/java/com/genius/gitget/profile/controller/ProfileController.java
- src/main/java/com/genius/gitget/profile/service/ProfileFacade.java
- src/main/java/com/genius/gitget/profile/service/ProfileFacadeService.java
- src/test/java/com/genius/gitget/profile/service/ProfileServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
feat/241profile-facade -> main 
</br>
- ProfileService 제거
- ProfileFacade & ProfileFacadeService 구현
- 테스트 코드 DCI 패턴 도입
</br>
</br>
#241 
</br>
> [FEAT] ProfileController Facade & DCI 패턴

- src/main/java/com/genius/gitget/challenge/certification/service/CertificationFacadeService.java
- src/main/java/com/genius/gitget/challenge/instance/facade/InstanceFacadeService.java
- src/main/java/com/genius/gitget/challenge/instance/facade/InstanceHomeFacadeService.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceDetailFacadeService.java
- src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
- src/main/java/com/genius/gitget/challenge/likes/facade/LikesFacadeService.java
- src/main/java/com/genius/gitget/challenge/myChallenge/facade/MyChallengeFacadeService.java
- src/main/java/com/genius/gitget/challenge/user/service/UserService.java
- src/main/java/com/genius/gitget/global/file/controller/FileTestController.java
- src/main/java/com/genius/gitget/global/file/controller/FilesController.java
- src/main/java/com/genius/gitget/global/file/service/FileService.java
- src/main/java/com/genius/gitget/global/file/service/FilesManager.java
- src/main/java/com/genius/gitget/global/file/service/LocalFileService.java
- src/main/java/com/genius/gitget/global/file/service/S3FileService.java
- src/main/java/com/genius/gitget/global/util/config/AppConfig.java
- src/main/java/com/genius/gitget/profile/service/ProfileFacadeService.java
- src/main/java/com/genius/gitget/topic/facade/TopicFacadeService.java
- src/test/java/com/genius/gitget/challenge/instance/controller/InstanceControllerTest.java
- src/test/java/com/genius/gitget/challenge/instance/service/InstanceFacadeTest.java
- src/test/java/com/genius/gitget/challenge/likes/controller/LikesControllerTest.java
- src/test/java/com/genius/gitget/global/file/service/FileUtilTest.java
- src/test/java/com/genius/gitget/payment/controller/PaymentControllerTest.java
- src/test/java/com/genius/gitget/profile/controller/ProfileControllerTest.java
- src/test/java/com/genius/gitget/topic/controller/TopicControllerTest.java
□ 기능 추가
□ 기능 삭제
☑ 리팩토링
□ 버그 수정
</br>
`refactor/237-files-layer-name` → `main`
</br>
</br>
</br>
#237
</br>
>
> [REFACTOR] Files 서비스 계층 이름 변경

- src/main/java/com/genius/gitget/global/security/controller/AuthController.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/249-jwt-api-set-header` → `main`
</br>
</br>
</br>
#249 
</br>
> [FEAT] JWT 발급 API에서 header 추가 설정

- src/main/java/com/genius/gitget/challenge/certification/controller/CertificationController.java
- src/main/java/com/genius/gitget/challenge/certification/controller/GithubController.java
- src/main/java/com/genius/gitget/challenge/instance/controller/InstanceDetailController.java
- src/main/java/com/genius/gitget/challenge/instance/controller/InstanceHomeController.java
- src/main/java/com/genius/gitget/challenge/likes/controller/LikesController.java
- src/main/java/com/genius/gitget/challenge/myChallenge/controller/MyChallengeController.java
- src/main/java/com/genius/gitget/global/security/controller/AuthController.java
- src/main/java/com/genius/gitget/global/util/annotation/GitGetUser.java
- src/main/java/com/genius/gitget/profile/controller/ProfileController.java
- src/main/java/com/genius/gitget/store/item/controller/StoreController.java
- src/main/java/com/genius/gitget/store/payment/controller/PaymentController.java
- src/main/java/com/genius/gitget/store/payment/controller/PaymentTossController.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/248-auth-custom-annotation` → `main`
</br>
> `@AuthenticationPrincipal` 어노테이션의 중복 코드를 제거하기 위해 `@GitGetUser` 커스텀 어노테이션을 작성하고 적용합니다.
</br>
</br>
#248 
</br>
>
> [FEAT] Spring security 관련 커스텀 어노테이션 생성 및 적용

- src/main/java/com/genius/gitget/challenge/user/service/UserService.java
- src/main/java/com/genius/gitget/profile/service/ProfileFacadeService.java
□ 기능 추가
□ 기능 삭제
☑ 버그 수정
</br>
`fix/261-member-withdrawal-bug` → `main`
</br>
</br>
</br>
#261 
</br>
>
> [FIX] 회원 탈퇴 이후, 로그인 버튼을 눌렀을 때 회원가입 페이지로 가지 않는 버그 픽스

- src/main/java/com/genius/gitget/challenge/certification/domain/Certification.java
- src/main/java/com/genius/gitget/challenge/certification/repository/CertificationRepository.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/260-certification-performance-improve` → `main`
</br>
</br>
</br>
#260 
</br>
> [FEAT] CertificationRepository 성능 개선

- src/main/java/com/genius/gitget/challenge/user/dto/LoginRequest.java
- src/main/java/com/genius/gitget/challenge/user/facade/UserFacade.java
- src/main/java/com/genius/gitget/challenge/user/facade/UserFacadeService.java
- src/main/java/com/genius/gitget/global/security/controller/AuthController.java
- src/main/java/com/genius/gitget/global/security/dto/GuestResponse.java
- src/main/resources/data.sql
- src/test/java/com/genius/gitget/challenge/user/domain/UserTest.java
- src/test/java/com/genius/gitget/profile/service/ProfileServiceTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`feat/266-test-account` → `main`
</br>
> 서비스를 체험할 수 있는 테스트 계정을 생성하고, FE에서 요청할 테스트 계정 로그인 API를 개발합니다.
</br>
</br>
#266 
</br>
> [FEAT] 테스트 계정 설정 및 API 개발

- src/main/java/com/genius/gitget/global/file/dto/FileEnv.java
- src/main/java/com/genius/gitget/global/file/dto/FileResponse.java
- src/main/java/com/genius/gitget/global/file/service/LocalFileService.java
- src/main/java/com/genius/gitget/global/file/service/S3FileService.java
- src/main/resources/data.sql
- src/test/java/com/genius/gitget/global/file/domain/FilesTest.java
☑ 기능 추가
□ 기능 삭제
□ 버그 수정
</br>
`refactor/270-file-response-fields` -> `main`
</br>
> Local 버전과 Production 버전에 따라 파일을 처리하는 로직을 분리합니다.
> Local 버전에서도 기존에 파일 URI를 반환하던 방식에서 Base64로 인코딩 한 문자열을 반환하는 방식으로 변경합니다.
> Production 버전에서는 이전 방식에서 변경하지 않습니다.
</br>
</br>
#270 
</br>
>
> [REFACTOR] 파일 시스템 버전에 따른 로직 분리
